#!/usr/bin/env python3
"""Ratchet physical C/C++ function lengths, including comments and blank lines.

Only tracked production sources are measured: build directories, moc output and
third-party code outside src never acquire accidental exemptions. Signatures,
not line numbers, identify functions across moves within a file and overloads.
"""

import argparse
from pathlib import Path
import subprocess
import sys

import lizard

SUFFIXES = {".c", ".cc", ".cpp", ".cxx", ".h", ".hh", ".hpp", ".hxx"}
NEW_LIMIT = 100
HARD_LIMIT = 200


def measure(root):
    tracked = subprocess.check_output(
        ["git", "-C", str(root), "ls-files", "-z", "--", "src"], text=True
    )
    lengths = {}
    for name in sorted(filter(None, tracked.split("\0"))):
        if Path(name).suffix.lower() not in SUFFIXES:
            continue
        path = root / name
        if not path.exists():  # a tracked file removed in the working tree
            continue
        for function in lizard.analyze_file(str(path)).function_list:
            signature = " ".join(function.long_name.split())
            key = f"{name}\t{signature}"
            length = function.end_line - function.start_line + 1
            # Platform alternatives sometimes define the same signature twice.
            # Check their maximum, so a shorter branch cannot mask a longer one.
            lengths[key] = max(length, lengths.get(key, 0))
    if not lengths:
        raise ValueError("no production C/C++ functions found")
    return lengths


def read_baseline(path):
    baseline = {}
    for number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        if not line or line.startswith("#"):
            continue
        try:
            count, source, signature = line.split("\t")
            length = int(count)
            if not 0 < length <= HARD_LIMIT or not source.startswith("src/") or not signature:
                raise ValueError
            key = f"{source}\t{signature}"
            if key in baseline:
                raise ValueError
        except ValueError as error:
            raise ValueError(f"{path}:{number}: invalid or duplicate baseline entry") from error
        baseline[key] = length
    if not baseline:
        raise ValueError(f"{path}: empty baseline")
    return baseline


def violations(lengths, baseline):
    errors = []
    for key, length in sorted(lengths.items()):
        limit = baseline.get(key, NEW_LIMIT)
        if length > HARD_LIMIT:
            errors.append(f"{key}: {length} lines exceeds the absolute limit {HARD_LIMIT}")
        elif length > limit:
            reason = "baseline" if key in baseline else "new function limit"
            errors.append(f"{key}: {length} lines exceeds {reason} {limit}")
    return errors


def write_baseline(path, lengths):
    path.write_text(
        "# Physical lines (signature through closing brace), including comments and blanks.\n"
        "# Generated by .github/scripts/check-function-length.py --write-baseline.\n"
        "# Every existing function is pinned; new functions may have at most 100 lines.\n"
        "# Decreases/removals are free. Increases require an explicit reviewed decision.\n"
        "# No baseline entry or source function may exceed 200 lines.\n"
        "# Format: length<TAB>source<TAB>normalized signature; platform duplicates use max.\n"
        + "".join(f"{lengths[key]}\t{key}\n" for key in sorted(lengths)),
        encoding="utf-8",
    )


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[2])
    parser.add_argument("--baseline", type=Path)
    parser.add_argument("--write-baseline", action="store_true")
    args = parser.parse_args()
    path = args.baseline or args.root / "tests/function-length-baseline.txt"
    try:
        lengths = measure(args.root)
        if args.write_baseline:
            too_long = {key: length for key, length in lengths.items() if length > HARD_LIMIT}
            if too_long:
                raise ValueError("cannot baseline functions over 200 lines: " + str(too_long))
            write_baseline(path, lengths)
        else:
            errors = violations(lengths, read_baseline(path))
            if errors:
                print("\n".join(errors), file=sys.stderr)
                return 1
        print(f"Function lengths: {len(lengths)} signatures, maximum {max(lengths.values())} lines; OK")
        return 0
    except (OSError, ValueError, subprocess.CalledProcessError) as error:
        print(f"function-length check failed: {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    sys.exit(main())
